site_name: ZryteZene's Docs
site_description: Documentation for ZryteZene's api.

site_url: https://thatcakeid.github.io/zz-docs

repo_url: https://github.com/ThatCakeID/zz-docs
repo_name: ThatCakeID/zz-docs

edit_uri: blob/main/docs/

copyright: Copyright &copy; 2023 ThatCakeID

nav:
  - Home: index.md
  - Contributing: contributing.md
  - Awesome: awesome.md
  - API:
    - Version: api/version.md
    - Auth: api/auth.md
    - User: api/user.md
    - Music: api/music.md
  - 'Offical Apps':
    - zz-cli: apps/zz-cli.md

theme:
  name: material
  font:
    text: 'Outfit'
    code: 'Roboto Mono'
  icon:
    logo: material/music-note-outline
    repo: fontawesome/brands/github
  palette:
    - scheme: purple
      media: "(prefers-color-scheme: light)"
      primary: blue
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy

plugins:
  - search
  - social:
      cards_font: 'Noto Sans'
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - footnotes
  - admonition
  - pymdownx.details

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ThatCakeID
      name: Discord
    - icon: fontawesome/brands/github
      link: https://github.com/ThatCakeID
      name: GitHub
    - icon: fontawesome/brands/git-alt
      link: https://git.theclashfruit.me/ThatCakeID
      name: Gitea